### ISSUE TITLE
Not generating a location

### ISSUE THREAD

**Issue by mathisono** [ab0tj/PiCrumbs#1]
I ran into your project a few months ago, but i didn't get around to setting it up until now... All was well untill i ran the program... 
## I just hangs and never transmits a location, Its not transmiting over the vhf tnc , and not putting out a packet over the INTERNET? I can supply the config but ive gone throu the config and dont think it the problem is there. Any ideas???

pi@kj6dzb-L ~/PiCrumbs $ sudo ./picrumbs -v
PiCrumbs 0.1

Using config file /etc/picrumbs.conf
Operating as kj6dzb-4
Found 2 APRS paths.
Successfully opened VHF TNC port /tmp/kisstnc at 9600 baud
Successfully opened GPS port /dev/ttyUSB0 at 4800 baud
Init finished!

---

73 Mathison

**Comment by ab0tj** [comment]
I can think of a few things that might apply. Does the TNC at /tmp/kisstnc work with other programs? Are you sure the GPS at /dev/ttyUSB0 runs at 4800 baud? Also, did you set the correct passcode for APRS-IS?

There are some “undocumented” command line options for debug info that may help, also. –z gps (show incoming info from the GPS), -z tnc (show packets in/out of the TNC) and –z is (show internet activity).

Hope that helps,

Alex

**Comment by mathisono** [comment]
works like a charm with xastir... kj6dzb-4

Q: dose the program support GPSD? Im using that to manage the usbgps. i
will test again with the Pi Tnc. and try –z gps (show incoming info from
the GPS), -z tnc (show packets in/out of the TNC) and –z is (show internet
activity).

73 Mathison kj6dzb

**Comment by ab0tj** [comment]
No, it doesn’t support GPSD yet, but that may change. That brings up a good point though, if GPSD is still running, PiCrumbs may not be able to access the serial port.

**Comment by mathisono** [comment]
I know better than to let gpsd sit on the ttyUSB0. Ive come to like gpsd as
that it automatically handles the device and allows multiple client
application to access it. For a bit, I was running the HSMM-PI & Xastir on
the same RPI.

I stoked to utilize this program on with our clubs new KX 3, as a 2m / 30m
aprs. My pressure is to set the location manually.

**Comment by ab0tj** [comment]
Actually, looks like I never did complete the support for a static location. I’ll take care of that when I get some time. As you can tell, it’s not a completely polished product, I just use it for my personal tracker and made the GitHub repo public for anyone that wanted to mess around with it.

Did the debug info give you any insight into what’s going on?

**Comment by ab0tj** [comment]
Hi Mathison,

I don't know if you're even still working with this, but I have switched to using GPSd now. That may fix the other issue you were having as well.

Thanks,
Alex AB0TJ
